#pragma once
#include "CoreMinimal.h"
#include "EDriverAnimMontageId.generated.h"

UENUM(BlueprintType)
enum class EDriverAnimMontageId : uint8 {
    Crash,
    DashHigh,
    DashLow,
    DashFailure,
    TrickSpinLeft,
    TrickSpinRight,
    TrickFlipLeft,
    TrickFlipRight,
    TrickFlipFront,
    TrickFlipBack,
    UseItemFront,
    UseItemBack,
    UseWisp,
    HitItem,
    AnotherSelectLeft,
    AnotherSelectRight,
    TauntLeft,
    TauntRight,
    FrustrateLeft,
    FrustrateRight,
    TrickCorkscrewLeft,
    TrickCorkscrewRight,
    MonstercarTransform,
    MonstercarReturn,
    GoalWin01,
    GoalWin02,
    GoalWin03,
    ShuntLeftLow,
    ShuntRightLow,
    ShuntLeftHigh,
    ShuntRightHigh,
    EnemySquashed,
    ShuntFrontLow,
    ShuntBackLow,
    ShuntFrontHigh,
    ShuntBackHigh,
    BodyCut,
    Anchor,
    GoalLose01,
    RivalWin,
    RivalLose,
    JumpChargeStart,
    JumpChargeLoop,
    JumpChargeCrouch,
    DriftNoStart,
    DriftNoStartLeft,
    DriftNoStartRight,
    Num,
};

