#pragma once
#include "CoreMinimal.h"
#include "ELobbySequenceState.generated.h"

UENUM(BlueprintType)
enum class ELobbySequenceState : uint8 {
    Idle,
    SelectCourse = 28,
    SelectCourseOnline,
    RuleSetting = 9,
    GroupSetting = 13,
    FriendList = 44,
    SelectCharaMachine = 2,
    PlayerProfile = 45,
    TodayRecord = 7,
    Garage = 35,
    CustomizeGadget = 38,
    Option = 40,
    Etcetera = Option,
    GameSettings,
    LobbyPlayerList = 60,
    NotificationWindow,
    EmoteWheel,
    NoticePopup = 66,
    DodonpaEvent = 6,
    LobbySearch = 72,
    LobbySearchComplete,
    WaitP2PConnection,
    FixPlayerData,
    ReturnedFromRaceToLobby,
    CheckLobbyHost,
    WaitingReceiveLobbyInitData,
    ChangeP2PRaceCycle,
    WaitingInTheLobby,
    WaitingInTheLobbyTimerEnd,
    LobbyRuleSetting,
    TransitionToFriendLobbyAlone,
    SelectGameMode,
    WaitingJoinMembersAloneHost,
    WaitingJoinMembers,
    CloseLobbyInvitationWindow,
    TryToEnterLobby,
    WaitForHostLobbyId,
    CheckMembers,
    CheckMembersWaiting,
    CheckMembersWaitTallying,
    SquadPopupWindow,
    SelectCourseResult,
    LobbyFinished,
    FestaTeamDirecting,
    FestaRuleInfo,
    FestaRentalGadgetInfo,
    FestaFixedRuleInfoWindow,
    ShowTipsWindow,
    ErrorWindow,
    SelectCourseWait,
    CheckJoinLobby,
    WaitingComeBackLobby,
    SubLevelCheck,
    EntryCheck,
    LobbyInit,
    BackToPrevSequence,
    QuitLobbyWindow,
    QuitLobbyEndWindow,
    SubFairPoint,
    SquadInRaceCheck,
    WaitSquadP2PConnectComplete,
    Exit,
};

