#pragma once
#include "CoreMinimal.h"
#include "EUnionRacerEvent.generated.h"

UENUM(BlueprintType)
enum class EUnionRacerEvent : uint8 {
    None,
    OnAcceleChange,
    OnDrifting,
    OnDriftCharge,
    OnDash,
    OnStartDash,
    OnLanding,
    OnSlipStream,
    OnStant,
    OnRivalTouch,
    OnSteeringLR,
    OnBoostEnd,
    OnBoostPad,
    OnHitTrackWall,
    OnHitTrackWallTemp,
    OnSpin,
    OnTransformVehicleType,
    OnItemHold,
    OnUseItem,
    OnGoal,
    OnTimeout,
    OnAddRing,
    OnDashFire,
    OnChangeRank,
    OnBack,
    OnChangeDashLevel,
    OnSelectDomain,
    OnSlipStreamMaxSpeed,
    OnDamaged,
    OnAttackSuccess,
    OnTrick,
    OnTrickSuccess,
    OnTrickCancel,
    OnMetamorphose,
    OnCourseOutRecovery,
    OnSlowDown,
    OnSignSummon,
    OnSlimeStart,
    OnSlimeEnd,
    OnSlimeCancel,
    OnPaintStart,
    OnPaintEnd,
    OnPaintCancel,
    OnDriftNoStart,
};

