#pragma once
#include "CoreMinimal.h"
#include "RacerDamageType.generated.h"

UENUM(BlueprintType)
enum class RacerDamageType : uint8 {
    Non,
    CarHit,
    EnemyLarge,
    EnemyMedium,
    EnemySmall,
    EnemySquashed,
    PaintShower,
    GimmickDecelLarge,
    Bollard,
    HomingPunch,
    RocketPunch,
    YellowDrill,
    ThornBall,
    MonsterTruckLarge,
    MonsterTruckSmall,
    KingBoomBoo,
    Anchor,
    AnchorAbort,
    BodyCut,
    BodyCutAbort,
    Slicer,
    SlicerAttack,
    Slime,
    Splash,
    SplashAccelStart,
    SplashAccelEnd,
    SplashStart,
    SplashEnd,
    Magnet,
    MagnetAttract,
    MagnetAbort,
    JadeGhost,
    JadeGhostAbort,
    CyanLaserStart,
    CyanLaserMove,
    CyanLaserEnd,
    WarpRingStart,
    WarpRingEnd,
    WarpRingAttackStart,
    WarpRingAttackEnd,
    BlackBombLv1,
    BlackBombLv2,
    BlackBombLv3,
    BlackBombSquashed,
    DarkChao,
    Shield,
    ShieldAbort,
    VioletVoid,
    Omochao,
    ItemLostBySlime,
    ItemLostByDarkChao,
    FootCut,
    Weight,
    RingStole,
    Num,
};

