#pragma once
#include "CoreMinimal.h"
#include "ECheatCheckParamType.generated.h"

UENUM(BlueprintType)
enum class ECheatCheckParamType : uint8 {
    None,
    MaxSpeedRunItem,
    MaxSpeedRun,
    MaxSpeedNotRun,
    RaceStartTiming,
    CheckpointNotPassed,
    CheckpointPassingTime,
    GoalTime,
    DriveFormItem,
    DriveFormBoatPlane,
    FrameAccelerationTime,
    SpeedAccelerationTime,
    FootCutCount,
    ElapseScoreByFootCut,
    TopElapseScoreAtFootCut,
    ShortWarpTotalDistance,
    OnlinePlayerPacket,
    ReSpotPosition,
    ItemUsedBeforeStart,
    ItemGetLog,
    ItemUsedCount,
    TeamTouchCount,
    TeamRingCount,
    TeamAirTrickount,
    TeamItemHitCount,
    TeamDriftDashCount,
    TeamSpinDriftCount,
    TeamTouchDashCount,
    TeamDashCount,
    TeamAttackCount,
    SuperTeamDash,
    SpeedValue,
    AccelValue,
    DashValue,
    HandlingValue,
    PowerValue,
    AllParamsTotalValue,
    DriverUsed,
    FrontPartsUsed,
    RearPartsUsed,
    TirePartsUsed,
    TotalCostOfGadgetsUsed,
    NumberOfGadgetsUsed,
    GhostHeader,
    GhostCheckpointPassing,
    TARanking,
    TAItemUsed,
    TAItemEffect,
    TADisabledGadgetsUsed,
    TAGadgetEffect,
    Num,
    Invalid = 255,
};

