#pragma once
#include "CoreMinimal.h"
#include "EControllerButtonTextureIndex.generated.h"

UENUM(BlueprintType)
enum class EControllerButtonTextureIndex : uint8 {
    L1,
    R1,
    L2,
    R2,
    L_Tmp1,
    R_Tmp1,
    L_Tmp2,
    R_Tmp2,
    Face_Tmp1,
    Face_Tmp2,
    Face_Tmp3,
    Face_Tmp4,
    FaceUp,
    FaceRight,
    FaceDown,
    FaceLeft,
    LStick,
    LStickUpDown,
    LStickLeftRight,
    LStickPush,
    LStickUp,
    LStickRight,
    LStickDown,
    LStickLeft,
    RStick,
    RStickUpDown,
    RStickLeftRight,
    RStickPush,
    RStickUp,
    RStickRight,
    RStickDown,
    RStickLeft,
    LStickRoll,
    RStickRoll,
    LStickTmp1,
    RStickTmp1,
    LStickTmp2,
    RStickTmp2,
    LStickTmp3,
    RStickTmp3,
    Cross,
    CrossUpDown,
    CrossLeftRight,
    CrossTmp1,
    CrossUp,
    CrossRight,
    CrossDown,
    CrossLeft,
    Start,
    Select,
    Center,
};

