#pragma once
#include "CoreMinimal.h"
#include "EOnlineErrorId.generated.h"

UENUM(BlueprintType)
enum class EOnlineErrorId : uint8 {
    NonError,
    CommonError,
    NoConnection,
    NoConnectionNotOnline,
    DisconnectHost,
    DisconnectHostNotOnline,
    DelayGameTime,
    NoInputSignal,
    ReverseRunRecoverCount,
    FailedToSynchronize,
    TimeOut,
    NoMatchFound,
    SquadHostAbortedMatch,
    SquadLobbyEntryBlocked,
    FailedLogin,
    FailedSaveServer,
    NotOnline,
    LogoutUser,
    NoOnlinePrivilege,
    ParentalControlled,
    XBOXCommunicationBlocked,
    HighTrafficProfile,
    NoMatchCrossPlayy,
    LobbyTooManyPlayers,
    NoLobby,
    HostKicked,
    HostBlocked,
    AlreadyInLobby,
    FailedCreatePrivateLobby,
    ForeverBan,
    TemporalBan,
    ForeverBanNotification,
    TemporalBanNotification,
    NoSquadLobby,
    DisconnectSquadHost,
    NoConncectionBackTopMenu,
    NoInternet,
    NotLatestApplication,
    PSNNotSignedIn,
    XBOXNetworkNotSignedIn,
    NewFestaStarted,
    CurrentFestaEnded,
    NewFreeContentsOpened,
    LegendCompeStarted,
    BanBackTopMenu,
    Wireless_EntryLobbyPlayerFull,
    Wireless_EntryLobbyNotExists,
    Wireless_UnMatchedRomVersion,
    Wireless_EntryLobbyInRace,
    Wireless_EntryFailedError,
    Wireless_CommonError,
    Wireless_ConnectionErrorNotOnline,
    LoginMaintenanceDisablePlay,
    LoginMaintenanceEnablePlayWithSchedule,
    LoginMaintenanceDisablePlayWithSchedule,
    LoginNsaIdTokenUserInfoRefresh,
    ExpiredShortLobbyId,
    NoMatchGuestAndHostLobbyType,
    Num,
};

