#pragma once
#include "CoreMinimal.h"
#include "ERewardGrandPrixRivalWinHonorId.generated.h"

UENUM(BlueprintType)
enum class ERewardGrandPrixRivalWinHonorId : uint8 {
    GrandPrix_RivalWin_Normal_LV01,
    GrandPrix_RivalWin_Normal_LV02,
    GrandPrix_RivalWin_Normal_LV03,
    GrandPrix_RivalWin_Normal_LV04,
    GrandPrix_RivalWin_Normal_LV05,
    GrandPrix_RivalWin_Normal_LV06,
    GrandPrix_RivalWin_Normal_LV07,
    GrandPrix_RivalWin_Normal_LV08,
    GrandPrix_RivalWin_Normal_LV09,
    GrandPrix_RivalWin_Normal_LV10,
    GrandPrix_RivalWin_High_LV01,
    GrandPrix_RivalWin_High_LV02,
    GrandPrix_RivalWin_High_LV03,
    GrandPrix_RivalWin_High_LV04,
    GrandPrix_RivalWin_High_LV05,
    GrandPrix_RivalWin_High_LV06,
    GrandPrix_RivalWin_High_LV07,
    GrandPrix_RivalWin_High_LV08,
    GrandPrix_RivalWin_High_LV09,
    GrandPrix_RivalWin_High_LV10,
    GrandPrix_RivalWin_Sonic_LV01,
    GrandPrix_RivalWin_Sonic_LV02,
    GrandPrix_RivalWin_Sonic_LV03,
    GrandPrix_RivalWin_Sonic_LV04,
    GrandPrix_RivalWin_Sonic_LV05,
    GrandPrix_RivalWin_Sonic_LV06,
    GrandPrix_RivalWin_Sonic_LV07,
    GrandPrix_RivalWin_Sonic_LV08,
    GrandPrix_RivalWin_Sonic_LV09,
    GrandPrix_RivalWin_Sonic_LV10,
    GrandPrix_RivalWin_SuperSonic_LV01,
    GrandPrix_RivalWin_SuperSonic_LV02,
    GrandPrix_RivalWin_SuperSonic_LV03,
    GrandPrix_RivalWin_SuperSonic_LV04,
    GrandPrix_RivalWin_SuperSonic_LV05,
    GrandPrix_RivalWin_SuperSonic_LV06,
    GrandPrix_RivalWin_SuperSonic_LV07,
    GrandPrix_RivalWin_SuperSonic_LV08,
    GrandPrix_RivalWin_SuperSonic_LV09,
    GrandPrix_RivalWin_SuperSonic_LV10,
    GrandPrix_RivalWin_Mirror_LV01,
    GrandPrix_RivalWin_Mirror_LV02,
    GrandPrix_RivalWin_Mirror_LV03,
    GrandPrix_RivalWin_Mirror_LV04,
    GrandPrix_RivalWin_Mirror_LV05,
    GrandPrix_RivalWin_Mirror_LV06,
    GrandPrix_RivalWin_Mirror_LV07,
    GrandPrix_RivalWin_Mirror_LV08,
    GrandPrix_RivalWin_Mirror_LV09,
    GrandPrix_RivalWin_Mirror_LV10,
};

