#pragma once
#include "CoreMinimal.h"
#include "EStatsEventId.generated.h"

UENUM(BlueprintType)
enum class EStatsEventId : uint8 {
    Unknown,
    TotalDrivingDistance,
    TotalPlayingTime,
    TotalRacesCount,
    TotalVictoryCount,
    UsedItemCount,
    AttackItemCount,
    BackAttackItemCount,
    SpecialItemBoxCount,
    StartDashCount,
    DriftDashCount,
    AirTrickCount,
    ChargeLv3Count,
    DashPanelCount,
    OvertakingBeforeGoalCount,
    RingsCount,
    ShortCutRingCount,
    SelectedTravelRingCount,
    SafetyDriver,
    FirstFastChargeCount,
    BoatJumpUpCount,
    PlaneTurnCount,
    SwitchQuickChargeCount,
    JustChargeDashCount,
    EnhanceRocketPunchCount,
    WarpRingCount,
    TouchDashCount,
    RingStoleCount,
    TechnicalDriftCount,
    SpinDriftHitCount,
    UltimateChargeCount,
    ScratchesCount,
    GadgetFragmentsCount,
    RedStarRingsCount,
    DonpaTicketsCount,
    GP_CompletionRacesCount,
    GP_VictoriesCount,
    GP_AllRacesVictoriesCount,
    GP_1stPlaceCount,
    GP_WonRivalCount,
    TimeTrialCount,
    TimeTrialSafetyDriver,
    TimeTrialItemBoxCount,
    FriendMatchCount,
    FriendFrandPrixCount,
    FriendPlayedWithCount,
    UsedMachineCount,
    UsedCharactersCount,
    WinCharactersCount,
    Num,
};

